services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=${RISINGWAVE_HOSTNAME}
      - DATABASE_PORT=${RISINGWAVE_PORT}
      - DATABASE_NAME=${RISINGWAVE_DATABASE}
      - DATABASE_USERNAME=${RISINGWAVE_USERNAME}
      - DATABASE_PASSWORD=${RISINGWAVE_PASSWORD}
    ports:
      - 1337:1337
    # volumes:
    #   - ./app:/srv/app
    depends_on:
      - risingwave
    command: 'strapi start'