services:

 # https://console.cloud.google.com/artifacts/docker/keephq/us-central1/keep?inv=1&invt=AbjkAQ&project=keephq
  keep-frontend:
    image: us-central1-docker.pkg.dev/keephq/keep/keep-ui:0.31.1
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_SECRET=secret
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - POSTHOG_KEY=phc_muk9qE3TfZsX3SZ9XxX52kCGJBclrjhkP9JxAQcm1PZ
      - POSTHOG_HOST=https://ingest.keephq.dev
      # - NEXT_PUBLIC_SENTRY_DSN=https://0d4d59e3105ffe8afa27dcb95a222009@o4505515398922240.ingest.us.sentry.io/4508258058764288
      - PUSHER_HOST=localhost
      - PUSHER_PORT=6001
      - PUSHER_APP_KEY=keepappkey
      - NEXT_PUBLIC_KEEP_VERSION=0.2.9
      - AUTH_TYPE=NOAUTH # AUTH_TYPE=SINGLE_TENANT
      - API_URL=http://keep-backend:8080
      - KEEP_DEFAULT_USERNAME=keep
      - KEEP_DEFAULT_PASSWORD=keep
  keep-backend:
    image: us-central1-docker.pkg.dev/keephq/keep/keep-api:0.31.1
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SECRET_MANAGER_TYPE=FILE
      - SECRET_MANAGER_DIRECTORY=/state
      - DATABASE_CONNECTION_STRING=postgresql://keep:keep@postgres/keep
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - PUSHER_APP_ID=1
      - PUSHER_APP_KEY=keepappkey
      - PUSHER_APP_SECRET=keepappsecret
      - PUSHER_HOST=keep-websocket-server
      - PUSHER_PORT=6001
      - USE_NGROK=false
      - API_URL=http://keep-backend-dev:8080
      - SENTRY_DISABLED=true

  keep-websocket:
    image: quay.io/soketi/soketi:1.4-16-debian
    ports:
      - "6001:6001"
      - "9601:9601"
    environment:
      - SOKETI_USER_AUTHENTICATION_TIMEOUT=3000
      - SOKETI_DEBUG=1
      - SOKETI_DEFAULT_APP_ID=1
      - SOKETI_DEFAULT_APP_KEY=keepappkey
      - SOKETI_DEFAULT_APP_SECRET=keepappsecret      


  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=keep
      - POSTGRES_PASSWORD=keep
      - POSTGRES_DB=keep
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
