services:
  
  postgres-data:
    image: "postgres:15"
    container_name: postgres-data
    # command: ["/bin/bash", "-c", "apt-get update && apt-get install -y postgresql-15-clickhouse-fdw && psql -v ON_ERROR_STOP=1 -U supabase_user -d supabase -c \"CREATE EXTENSION clickhouse_fdw; CREATE SERVER clickhouse_server FOREIGN DATA WRAPPER clickhouse_fdw OPTIONS (host 'clickhouse', port '9000', database 'default'); CREATE USER MAPPING FOR supabase_user SERVER clickhouse_server OPTIONS (user '', password '');\" && postgres"] # Install extension and create server
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
    environment:
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=data
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    expose:
      - "5432"
    ports:
      - 5433:5432
    volumes:
      - ./applications/postgres-data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - "postgres-data:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres-data:
