services:

  postgres-risingwave-dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.0
    command: run --debug --profile=postgres_dbt --target=dev --fail-fast
    depends_on:
      postgres-risingwave:
        condition: service_healthy
        restart: true
    expose:
      - 8080
    ports:
      - 8086:8080
    volumes:
      - ./applications/postgres-risingwave/dbt/:/usr/app/dbt/
      - ./applications/postgres-risingwave/profiles/profiles.yml:/root/.dbt/profiles.yml
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda:29092
      KAFKA_PRODUCER_TOPIC: ais-data
