services:

  redis:
    image: redis:6
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    image: directus/directus:11.3.2
    ports:
      - 8055:8055
    volumes:
      - ./applications/directus/uploads:/directus/uploads
      - ./applications/directus/extensions:/directus/extensions
    depends_on:
      risingwave:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SECRET: "replace-with-secure-random-value"

      # DB_CLIENT: "pg"
      # DB_HOST: ${POSTGRES_HOST}
      # DB_PORT: ${POSTGRES_PORT}
      # DB_DATABASE: ${POSTGRES_DB}
      # DB_USER: ${POSTGRES_USER}
      # DB_PASSWORD: ${POSTGRES_PASSWORD}

      DB_CLIENT: "postgres"
      DB_HOST: ${RISINGWAVE_HOSTNAME}
      DB_PORT: ${RISINGWAVE_PORT}
      DB_DATABASE: ${RISINGWAVE_DATABASE}
      DB_USER: ${RISINGWAVE_USERNAME}
      DB_PASSWORD: ${RISINGWAVE_PASSWORD}

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://redis:6379"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"

    # Environment variables can also be defined in a file (for example `.env`):
    # env_file:
    #	  - .env