services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.23.6
    restart: unless-stopped
    environment:
      ENCRYPTION: $(openssl rand -hex 32)\
      prts:
      - "8090:8090"
    volumes:
      - pocketbase:/pb_data
      # - /path/to/public:/pb_public # optional
      # - /path/to/hooks:/pb_hooks # optional
    healthcheck: # optional, recommended since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pocketbase: