postgres_dbt:
  outputs:
    dev:
      type: postgres      
      host: postgres-risingwave
      port: 5432
      user: postgres
      password: postgres
      dbname: metadata
      schema: public
      threads: 1
  target: dev
