risingwave_dbt:
  outputs:
    dev:
      type: risingwave      
      host: risingwave-standalone
      port: 4566
      user: root
      password: root
      dbname: dev
      schema: public
      threads: 1
  target: dev
